### ISSUE TITLE
The running command is inconsistent with which in the README.md . And some code is missing in gar_mlp.py.

### ISSUE THREAD

**Issue by Isuxiz** [zfnWong/GAR#2]
1. There is actually no `GCGAN` folder, I presume it refers to the `GAR` folder, does it?
2. Assuming that the conjecture in 1 is correct, executing `python3 main.py --gpu_id 0 --dataset CiteULike --embed_meth node2vec --agg_meth none --gan_model garmlp --real_lys [200,200] --real_act tanh --sim_coe 0.1`  (the command provided by README.md) in `GAR` will raise an error: the `GARMLP` object does not have the `get_ranked_rating` attribute. It seems that the uploaded code is incomplete.

**Comment by zfnWong** [comment]
Thank you for revealing this issue in time. We have fixed it and you can access the repo to follow the modifications. Modifications include:
1) Move the `main.py` from GAR folder to the project directory. This fix problem 1 in you email.
2) Add the `get_ranked_rating()`&nbsp;function to `gar_mlp.py` in GAR folder. This fix problem 2.
3) Modify `README.md`.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zfnWong/GAR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月28日(星期天) 凌晨2:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zfnWong/GAR] The running command is inconsistent with which in the README.md . And some code is missing in gar_mlp.py. (Issue #2)





  
There is actually no GCGAN folder, I presume it refers to the GAR folder, does it?
 
Assuming that the conjecture in 1 is correct, executing python3 main.py --gpu_id 0 --dataset CiteULike --embed_meth node2vec --agg_meth none --gan_model garmlp --real_lys [200,200] --real_act tanh --sim_coe 0.1  (the command provided by README.md) in GAR will raise an error: the GARMLP object does not have the get_ranked_rating attribute. It seems that the uploaded code is incomplete.
